# Generated by Django 5.2.1 on 2025-05-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
