stages:
  - test
  - build
  - deploy

variables:
  ENV_NAME: "prod"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"
  SSH_PRIVATE_KEY_PATH: "/tmp/deploy_key.pem"
  PROJECT_DIR: "/home/ubuntu/hackaton_assignment"

.default_job: &default_job
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apt-get update && apt-get install -y openssh-client git bash curl
    - mkdir -p ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - echo "$SSH_PRIVATE_KEY" > $SSH_PRIVATE_KEY_PATH
    - chmod 600 $SSH_PRIVATE_KEY_PATH
    - export GIT_SSH_COMMAND="ssh -i $SSH_PRIVATE_KEY_PATH -o UserKnownHostsFile=~/.ssh/known_hosts -o StrictHostKeyChecking=yes"

# =========================
# Backend tests execution
# =========================

test_backend:
  <<: *default_job
  stage: test
  image: python:3.11
  services:
    - postgres:15
  variables:
    ENV_NAME: "prod"
    POSTGRES_HOST: db
  before_script:
    - pip install -r backend/requirements.txt
    - cd backend
  script:
    - python manage.py test --verbosity=2
  allow_failure: false
  retry: 1


# =========================
# Build Docker images for environment
# =========================

build:
  <<: *default_job
  stage: build
  script:
    - docker compose -f docker-compose.${ENV_NAME}.yml build
  allow_failure: false

# =========================
# Deploy application to production server
# =========================

deploy_prod:
  <<: *default_job
  stage: deploy
  only:
    - main
  environment:
    name: production
    url: http://18.197.176.80
  script:
    - ssh -o StrictHostKeyChecking=yes -i $SSH_PRIVATE_KEY_PATH ubuntu@18.197.176.80 "
      cd $PROJECT_DIR &&
      git reset --hard &&
      git pull origin main &&
      docker compose -f docker-compose.prod.yml down &&
      docker compose -f docker-compose.prod.yml up -d --build &&
      docker image prune -f
      "
  allow_failure: false
  retry: 2
