stages:
  - build
  - deploy

variables:
  ENV_NAME: "prod"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"
  PROJECT_DIR: "/home/ubuntu/hackaton_assignment"

.default_job: &default_job
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache openssh git bash curl
    - mkdir -p ~/.ssh
    - cat "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=~/.ssh/known_hosts -o StrictHostKeyChecking=yes"

build:
  <<: *default_job
  stage: build
  script:
    - docker compose -f docker-compose.${ENV_NAME}.yml build
  allow_failure: false

deploy_prod:
  <<: *default_job
  stage: deploy
  only:
    - main
  environment:
    name: production
    url: https://your-production-url.example.com
  script:
    - ssh -o StrictHostKeyChecking=yes -i ~/.ssh/id_rsa ubuntu@18.197.176.80 '
      set -e
      cd "$PROJECT_DIR"
      git reset --hard
      git pull origin main
      docker compose -f docker-compose.prod.yml down
      docker compose -f docker-compose.prod.yml up -d --build
      docker image prune -f
      '
  allow_failure: false
  retry: 2