stages:
  - build
  - deploy

variables:
  PROJECT_DIR: "/home/ubuntu/hackaton_assignment"

.default_job: &default_job
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache openssh git bash curl
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - |
      echo -e "Host lntu-server\n\tHostName 18.197.176.80\n\tUser ubuntu\n\tIdentityFile ~/.ssh/id_rsa\n\tStrictHostKeyChecking no" > ~/.ssh/config
    - chmod 600 ~/.ssh/config

build:
  <<: *default_job
  stage: build
  script:
    - docker compose -f docker-compose.prod.yml build

deploy_prod:
  <<: *default_job
  stage: deploy
  script:
    - ssh lntu-server '
      cd "$PROJECT_DIR"
      git pull origin main
      docker compose -f docker-compose.prod.yml down
      docker compose -f docker-compose.prod.yml up -d --build
      docker image prune -f
      '
