up:
	docker-compose up --build

down:
	docker-compose down -v

migrate:
	docker-compose exec backend python manage.py migrate

superuser:
	docker-compose exec backend python manage.py createsuperuser
